services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      APP_PORT: ${APP_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    container_name: tibber-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  pgdata: